// Code generated by protoc-gen-gogo.
// source: message.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	CastMessage
	AuthChallenge
	AuthResponse
	AuthError
	SeviceAuthMessage
*/
package cast

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

// Always pass a version of the protocol for future compatibility
// requirements.
type CastMessage_ProtocolVersion int32

const (
	CastMessage_CASTV2_1_0 CastMessage_ProtocolVersion = 0
)

var CastMessage_ProtocolVersion_name = map[int32]string{
	0: "CASTV2_1_0",
}
var CastMessage_ProtocolVersion_value = map[string]int32{
	"CASTV2_1_0": 0,
}

func (x CastMessage_ProtocolVersion) Enum() *CastMessage_ProtocolVersion {
	p := new(CastMessage_ProtocolVersion)
	*p = x
	return p
}
func (x CastMessage_ProtocolVersion) String() string {
	return proto.EnumName(CastMessage_ProtocolVersion_name, int32(x))
}
func (x *CastMessage_ProtocolVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CastMessage_ProtocolVersion_value, data, "CastMessage_ProtocolVersion")
	if err != nil {
		return err
	}
	*x = CastMessage_ProtocolVersion(value)
	return nil
}
func (CastMessage_ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorMessages, []int{0, 0}
}

// What type of data do we have in this message.
type CastMessage_PayloadType int32

const (
	CastMessage_STRING CastMessage_PayloadType = 0
	CastMessage_BINARY CastMessage_PayloadType = 1
)

var CastMessage_PayloadType_name = map[int32]string{
	0: "STRING",
	1: "BINARY",
}
var CastMessage_PayloadType_value = map[string]int32{
	"STRING": 0,
	"BINARY": 1,
}

func (x CastMessage_PayloadType) Enum() *CastMessage_PayloadType {
	p := new(CastMessage_PayloadType)
	*p = x
	return p
}
func (x CastMessage_PayloadType) String() string {
	return proto.EnumName(CastMessage_PayloadType_name, int32(x))
}
func (x *CastMessage_PayloadType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CastMessage_PayloadType_value, data, "CastMessage_PayloadType")
	if err != nil {
		return err
	}
	*x = CastMessage_PayloadType(value)
	return nil
}
func (CastMessage_PayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorMessages, []int{0, 1}
}

type AuthError_ErrorType int32

const (
	AuthError_INTERNAL_ERROR AuthError_ErrorType = 0
	AuthError_NO_TLS         AuthError_ErrorType = 1
)

var AuthError_ErrorType_name = map[int32]string{
	0: "INTERNAL_ERROR",
	1: "NO_TLS",
}
var AuthError_ErrorType_value = map[string]int32{
	"INTERNAL_ERROR": 0,
	"NO_TLS":         1,
}

func (x AuthError_ErrorType) Enum() *AuthError_ErrorType {
	p := new(AuthError_ErrorType)
	*p = x
	return p
}
func (x AuthError_ErrorType) String() string {
	return proto.EnumName(AuthError_ErrorType_name, int32(x))
}
func (x *AuthError_ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthError_ErrorType_value, data, "AuthError_ErrorType")
	if err != nil {
		return err
	}
	*x = AuthError_ErrorType(value)
	return nil
}
func (AuthError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorMessages, []int{3, 0}
}

type CastMessage struct {
	ProtocolVersion *CastMessage_ProtocolVersion `protobuf:"varint,1,req,name=protocol_version,enum=internal.CastMessage_ProtocolVersion" json:"protocol_version,omitempty"`
	// source and destination ids identify the origin and destination of the
	// message.  They are used to route messages between endpoints that share a
	// device-to-device channel.
	//
	// For messages between applications:
	//   - The sender application id is a unique identifier generated on behalf of
	//     the sender application.
	//   - The receiver id is always the the session id for the application.
	//
	// For messages to or from the sender or receiver platform, the special ids
	// 'sender-0' and 'receiver-0' can be used.
	//
	// For messages intended for all endpoints using a given channel, the
	// wildcard destination_id '*' can be used.
	SourceId      *string `protobuf:"bytes,2,req,name=source_id" json:"source_id,omitempty"`
	DestinationId *string `protobuf:"bytes,3,req,name=destination_id" json:"destination_id,omitempty"`
	// This is the core multiplexing key.  All messages are sent on a namespace
	// and endpoints sharing a channel listen on one or more namespaces.  The
	// namespace defines the protocol and semantics of the message.
	Namespace   *string                  `protobuf:"bytes,4,req,name=namespace" json:"namespace,omitempty"`
	PayloadType *CastMessage_PayloadType `protobuf:"varint,5,req,name=payload_type,enum=internal.CastMessage_PayloadType" json:"payload_type,omitempty"`
	// Depending on payload_type, exactly one of the following optional fields
	// will always be set.
	PayloadUtf8      *string `protobuf:"bytes,6,opt,name=payload_utf8" json:"payload_utf8,omitempty"`
	PayloadBinary    []byte  `protobuf:"bytes,7,opt,name=payload_binary" json:"payload_binary,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CastMessage) Reset()                    { *m = CastMessage{} }
func (m *CastMessage) String() string            { return proto.CompactTextString(m) }
func (*CastMessage) ProtoMessage()               {}
func (*CastMessage) Descriptor() ([]byte, []int) { return fileDescriptorMessages, []int{0} }

func (m *CastMessage) GetProtocolVersion() CastMessage_ProtocolVersion {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return CastMessage_CASTV2_1_0
}

func (m *CastMessage) GetSourceId() string {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return ""
}

func (m *CastMessage) GetDestinationId() string {
	if m != nil && m.DestinationId != nil {
		return *m.DestinationId
	}
	return ""
}

func (m *CastMessage) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *CastMessage) GetPayloadType() CastMessage_PayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return CastMessage_STRING
}

func (m *CastMessage) GetPayloadUtf8() string {
	if m != nil && m.PayloadUtf8 != nil {
		return *m.PayloadUtf8
	}
	return ""
}

func (m *CastMessage) GetPayloadBinary() []byte {
	if m != nil {
		return m.PayloadBinary
	}
	return nil
}

// Messages for authentication protocol between a sender and a receiver.
type AuthChallenge struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AuthChallenge) Reset()                    { *m = AuthChallenge{} }
func (m *AuthChallenge) String() string            { return proto.CompactTextString(m) }
func (*AuthChallenge) ProtoMessage()               {}
func (*AuthChallenge) Descriptor() ([]byte, []int) { return fileDescriptorMessages, []int{1} }

type AuthResponse struct {
	Signature             []byte `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	ClientAuthCertificate []byte `protobuf:"bytes,2,req,name=client_auth_certificate" json:"client_auth_certificate,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptorMessages, []int{2} }

func (m *AuthResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AuthResponse) GetClientAuthCertificate() []byte {
	if m != nil {
		return m.ClientAuthCertificate
	}
	return nil
}

type AuthError struct {
	ErrorType        *AuthError_ErrorType `protobuf:"varint,1,req,name=error_type,enum=internal.AuthError_ErrorType" json:"error_type,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AuthError) Reset()                    { *m = AuthError{} }
func (m *AuthError) String() string            { return proto.CompactTextString(m) }
func (*AuthError) ProtoMessage()               {}
func (*AuthError) Descriptor() ([]byte, []int) { return fileDescriptorMessages, []int{3} }

func (m *AuthError) GetErrorType() AuthError_ErrorType {
	if m != nil && m.ErrorType != nil {
		return *m.ErrorType
	}
	return AuthError_INTERNAL_ERROR
}

type SeviceAuthMessage struct {
	// Request fields
	Challenge *AuthChallenge `protobuf:"bytes,1,opt,name=challenge" json:"challenge,omitempty"`
	// Response fields
	Response         *AuthResponse `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Error            *AuthError    `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SeviceAuthMessage) Reset()                    { *m = SeviceAuthMessage{} }
func (m *SeviceAuthMessage) String() string            { return proto.CompactTextString(m) }
func (*SeviceAuthMessage) ProtoMessage()               {}
func (*SeviceAuthMessage) Descriptor() ([]byte, []int) { return fileDescriptorMessages, []int{4} }

func (m *SeviceAuthMessage) GetChallenge() *AuthChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *SeviceAuthMessage) GetResponse() *AuthResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SeviceAuthMessage) GetError() *AuthError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CastMessage)(nil), "internal.CastMessage")
	proto.RegisterType((*AuthChallenge)(nil), "internal.AuthChallenge")
	proto.RegisterType((*AuthResponse)(nil), "internal.AuthResponse")
	proto.RegisterType((*AuthError)(nil), "internal.AuthError")
	proto.RegisterType((*SeviceAuthMessage)(nil), "internal.SeviceAuthMessage")
	proto.RegisterEnum("internal.CastMessage_ProtocolVersion", CastMessage_ProtocolVersion_name, CastMessage_ProtocolVersion_value)
	proto.RegisterEnum("internal.CastMessage_PayloadType", CastMessage_PayloadType_name, CastMessage_PayloadType_value)
	proto.RegisterEnum("internal.AuthError_ErrorType", AuthError_ErrorType_name, AuthError_ErrorType_value)
}

var fileDescriptorMessages = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0x51, 0x6b, 0xdb, 0x30,
	0x14, 0x85, 0xeb, 0x74, 0xed, 0xea, 0x1b, 0xcf, 0x4d, 0xb5, 0xd1, 0xfa, 0x65, 0xac, 0x35, 0x14,
	0xc2, 0x06, 0x66, 0xcd, 0xcb, 0xf6, 0x36, 0x92, 0x10, 0xb6, 0x40, 0xe7, 0x0e, 0xc7, 0x14, 0xf6,
	0x24, 0x34, 0xe7, 0x36, 0x15, 0xf3, 0xa4, 0x20, 0x29, 0x85, 0xfc, 0x88, 0xfd, 0xa4, 0xfd, 0xb7,
	0x49, 0x72, 0xe3, 0x36, 0x63, 0x7d, 0x09, 0xca, 0xe1, 0xbb, 0x3a, 0xf7, 0x1c, 0x0b, 0xe2, 0x5f,
	0xa8, 0x35, 0x5b, 0xa0, 0xce, 0x96, 0x4a, 0x1a, 0x49, 0x0e, 0xb8, 0x30, 0xa8, 0x04, 0xab, 0xd3,
	0x3f, 0x1d, 0xe8, 0x8e, 0x99, 0x36, 0x5f, 0x1b, 0x80, 0x7c, 0x82, 0x9e, 0x47, 0x2a, 0x59, 0xd3,
	0x3b, 0x54, 0x9a, 0x4b, 0x91, 0x04, 0xa7, 0x9d, 0x7e, 0x3c, 0x38, 0xcf, 0x36, 0x43, 0xd9, 0xa3,
	0x81, 0xec, 0xdb, 0x3d, 0x7d, 0xdd, 0xc0, 0xe4, 0x08, 0x42, 0x2d, 0x57, 0xaa, 0x42, 0xca, 0xe7,
	0x49, 0xc7, 0x4e, 0x86, 0xe4, 0x18, 0xe2, 0x39, 0x6a, 0xc3, 0x05, 0x33, 0x96, 0x70, 0xfa, 0xae,
	0xd7, 0x2d, 0x2a, 0x98, 0xdd, 0x6c, 0xc9, 0x2a, 0x4c, 0x9e, 0x79, 0xe9, 0x03, 0x44, 0x4b, 0xb6,
	0xae, 0x25, 0x9b, 0x53, 0xb3, 0x5e, 0x62, 0xb2, 0xe7, 0xad, 0xcf, 0x9e, 0xb0, 0x6e, 0xc8, 0xd2,
	0x82, 0xe4, 0xd5, 0xc3, 0xe0, 0xca, 0xdc, 0x7c, 0x4c, 0xf6, 0x4f, 0x83, 0xc6, 0x79, 0xa3, 0xfe,
	0xb0, 0xf6, 0x6a, 0x9d, 0x3c, 0xb7, 0x7a, 0x94, 0x9e, 0xc1, 0xe1, 0xbf, 0x7b, 0xc7, 0x00, 0xe3,
	0xe1, 0xac, 0xbc, 0x1e, 0xd0, 0x0b, 0xfa, 0xbe, 0xb7, 0x93, 0x9e, 0x43, 0xf7, 0xf1, 0xfd, 0x00,
	0xfb, 0xb3, 0xb2, 0x98, 0xe6, 0x9f, 0x7b, 0x3b, 0xee, 0x3c, 0x9a, 0xe6, 0xc3, 0xe2, 0x7b, 0x2f,
	0x48, 0x0f, 0xe1, 0xc5, 0x70, 0x65, 0x6e, 0xc7, 0xb7, 0xac, 0xae, 0x51, 0x2c, 0x30, 0x1d, 0x41,
	0xe4, 0x84, 0xc2, 0xc6, 0x92, 0x42, 0xa3, 0xef, 0x83, 0x2f, 0x6c, 0xf4, 0x95, 0x42, 0xdf, 0x64,
	0x44, 0xde, 0xc0, 0x49, 0x55, 0x73, 0x14, 0x86, 0x32, 0x4b, 0xd2, 0x0a, 0x95, 0xe1, 0x37, 0xbc,
	0x62, 0x06, 0x7d, 0x61, 0x51, 0xfa, 0x13, 0x42, 0x77, 0xc7, 0x44, 0x29, 0xa9, 0xc8, 0x05, 0x00,
	0xba, 0x43, 0x53, 0x48, 0xf3, 0x2d, 0x5e, 0x3f, 0x14, 0xd2, 0x82, 0x99, 0xff, 0x75, 0xcb, 0xa6,
	0xef, 0x20, 0x6c, 0xff, 0x10, 0x02, 0xf1, 0x34, 0x2f, 0x27, 0x45, 0x3e, 0xbc, 0xa4, 0x93, 0xa2,
	0xb8, 0x2a, 0x9a, 0x04, 0xf9, 0x15, 0x2d, 0x2f, 0x67, 0x36, 0xc1, 0xef, 0x00, 0x8e, 0x66, 0x78,
	0xc7, 0x2b, 0x74, 0x57, 0x6d, 0xde, 0xc1, 0x5b, 0x08, 0xab, 0x4d, 0x26, 0x6b, 0x1a, 0xf4, 0xbb,
	0x83, 0x93, 0x6d, 0xd3, 0x36, 0x32, 0xe9, 0xc3, 0x81, 0xba, 0x8f, 0x6b, 0x03, 0x38, 0xf4, 0x78,
	0x1b, 0x6d, 0xcb, 0x48, 0x61, 0xcf, 0x67, 0xb1, 0x0f, 0xc0, 0x61, 0x2f, 0xff, 0x13, 0x63, 0xd4,
	0xf9, 0xb2, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x13, 0x72, 0x5e, 0x58, 0xb0, 0x02, 0x00, 0x00,
}
